### PR TITLE
Fix versioning issue with 2 digits

### PR DESCRIPTION
**Pull request by gegles**
I was able to kitchen converge. Please also push it to http://supermarket.chef.io/.

Thanks!

### CODE REVIEW

**Comment by gegles** [comment]
@hildjj any hope you can merge this in and push the new recipe version to http://supermarket.chef.io/ ?

**Comment by hildjj** [comment]
It's been years since I touched chef.  Remind me how to push the recipe, please?

**Comment by gegles** [comment]
Ah, good question, I sorta tried to do it, but did not quite succeed...

Something like this:

Share your cookbook with: `knife cookbook site share COOKBOOK_NAME CATEGORY (options)`

More info [here](https://docs.chef.io/knife_cookbook_site.html#share)

Hopefully you succeed as only you can push a new version.... 

Cheers. G.

**Comment by hildjj** [comment]
I could transfer ownership of it to you on supermarket, as well as here, if you like.

**Comment by gegles** [comment]
Sounds good, I can take it from here... ;-) 

Thanks!

**Comment by hkpeprah** [comment]
Did this ever get pushed?

**Pull request merged**
